export enum AnomalyCategory {
  TERRAIN = 'TERRAIN',
  BIOME = 'BIOME',
  STRUCTURE = 'STRUCTURE',
  PHYSICS = 'PHYSICS',
  MOVEMENT = 'MOVEMENT',
  FLUID = 'FLUID',
  REDSTONE = 'REDSTONE',
  LIGHTING = 'LIGHTING',
  WEATHER = 'WEATHER',
  SOUND = 'SOUND',
  NAVIGATION = 'NAVIGATION',
  ENTITY = 'ENTITY',
  DIMENSIONAL = 'DIMENSIONAL',
  HISTORICAL = 'HISTORICAL',
  SPATIAL = 'SPATIAL',
  UNKNOWN = 'UNKNOWN',
}

export interface AnomalyDefinition {
  id: string;
  name: string;
  category: AnomalyCategory;
  baseWeight: number;
  minRegimeTier: number; // 0=Normal, 1=Amplified, 2=Great Sea, 3=Outer World, 4=Farlands, 5=Ultra Deep
  conflictTag: string;
  description: string;
  mechanicalEffect: string;
}

export const ANOMALIES: AnomalyDefinition[] = [
  {
    id: 'anomalousworld:elytra_propulsion_failure',
    name: 'Kinetic Quenching',
    category: AnomalyCategory.MOVEMENT,
    baseWeight: 1.3,
    minRegimeTier: 3,
    conflictTag: 'propulsion',
    description: 'Firework rockets ignite visually with sparks, but provide zero kinetic acceleration to Elytra gliders.',
    mechanicalEffect: 'Elytra velocity impulse scaled by 0.0x',
  },
  {
    id: 'anomalousworld:gravitational_drift',
    name: 'Gravitational Attenuation',
    category: AnomalyCategory.PHYSICS,
    baseWeight: 1.1,
    minRegimeTier: 1,
    conflictTag: 'gravity',
    description: 'Downward terminal velocity and fall acceleration are softened by 60%, creating floating, low-gravity descents.',
    mechanicalEffect: 'Vertical acceleration scaled by 0.40x',
  },
  {
    id: 'anomalousworld:f3_coordinate_malfunction',
    name: 'F3 Telemetry Collapse & Glitch',
    category: AnomalyCategory.NAVIGATION,
    baseWeight: 1.6,
    minRegimeTier: 2,
    conflictTag: 'hud_telemetry',
    description: 'The F3 debug screen telemetry malfunctions severely. Coordinates fluctuate with erratic rapid offsets, display garbled Unicode runes (e.g. §k???§r), flip axes, and report "Facing: undefined".',
    mechanicalEffect: 'F3 Debug XYZ strings scrambled with rapid jitter & corrupted glyphs',
  },
  {
    id: 'anomalousworld:compass_flux',
    name: 'Polar Inversion',
    category: AnomalyCategory.NAVIGATION,
    baseWeight: 1.4,
    minRegimeTier: 2,
    conflictTag: 'compass_needle',
    description: 'Magnetic poles collapse into erratic oscillation. Compasses spin aimlessly and in-game map pointers jitter wildly.',
    mechanicalEffect: 'Compass needle heading randomly oscillates +/- 180°',
  },
  {
    id: 'anomalousworld:fluid_stasis',
    name: 'Hydrostatic Viscosity',
    category: AnomalyCategory.FLUID,
    baseWeight: 1.2,
    minRegimeTier: 2,
    conflictTag: 'fluid_flow',
    description: 'Water and lava cascades freeze into thick, sluggish currents that take up to 4x longer to flow or recognize drops.',
    mechanicalEffect: 'Fluid tick rate reduced to 25% speed',
  },
  {
    id: 'anomalousworld:auroral_resonance',
    name: 'Auroral Shimmer',
    category: AnomalyCategory.LIGHTING,
    baseWeight: 0.9,
    minRegimeTier: 3,
    conflictTag: 'atmosphere_visual',
    description: 'High-altitude curtains of emerald and violet luminescence ripple across the subterranean ceiling and sky.',
    mechanicalEffect: 'Subterranean ambient phosphorescence active',
  },
  {
    id: 'anomalousworld:lattice_fracture',
    name: 'Orthogonal Lattice',
    category: AnomalyCategory.TERRAIN,
    baseWeight: 2.6,
    minRegimeTier: 4,
    conflictTag: 'terrain_geometry',
    description: 'Mathematical coordinate overflow transforms solid stone into an infinite 32-meter square matrix of tunnels.',
    mechanicalEffect: 'Evaluates 3D Farlands Lattice Equation',
  },
  {
    id: 'anomalousworld:mist_veil',
    name: 'Spokeland Mist',
    category: AnomalyCategory.WEATHER,
    baseWeight: 1.0,
    minRegimeTier: 2,
    conflictTag: 'atmosphere',
    description: 'Opaque volumetric fog blankets the landscape, restricting vision to 18 blocks and filtering ambient sky colors.',
    mechanicalEffect: 'Client fog distance clamped to 18 blocks',
  },
  {
    id: 'anomalousworld:historical_echo',
    name: 'Architectural Resonance',
    category: AnomalyCategory.HISTORICAL,
    baseWeight: 0.5,
    minRegimeTier: 3,
    conflictTag: 'structures',
    description: 'Uncannily familiar cobblestone foundations, mineshafts, or tower fragments generate deeply buried in virgin stone.',
    mechanicalEffect: 'Spawns ambiguous player-like structure echo (50-95% similarity)',
  },
  {
    id: 'anomalousworld:acoustic_echo',
    name: 'Subterranean Resonator',
    category: AnomalyCategory.SOUND,
    baseWeight: 1.0,
    minRegimeTier: 2,
    conflictTag: 'sound',
    description: 'Mining impacts, footsteps, and mob cries trigger delayed acoustic reverberations from deep underground.',
    mechanicalEffect: 'Audio sound events echoed with 450ms stereo delay',
  },
  {
    id: 'anomalousworld:optical_twilight',
    name: 'Photonic Absorption',
    category: AnomalyCategory.LIGHTING,
    baseWeight: 1.0,
    minRegimeTier: 3,
    conflictTag: 'lighting',
    description: 'Torches and lanterns suffer rapid light attenuation; light level 15 drops to zero within only 7 radial blocks.',
    mechanicalEffect: 'Block light emission attenuation steepened by 2x',
  },
  {
    id: 'anomalousworld:monolith_spires',
    name: 'Geological Spires',
    category: AnomalyCategory.TERRAIN,
    baseWeight: 1.5,
    minRegimeTier: 1,
    conflictTag: 'terrain_geometry',
    description: 'Single-chunk sheer basalt and granite monoliths shoot straight up past cloud level into the upper stratosphere.',
    mechanicalEffect: 'Terrain elevation boosted to Y=280-319',
  },
  {
    id: 'anomalousworld:underworld_fissure',
    name: 'Abyssal Fracture',
    category: AnomalyCategory.DIMENSIONAL,
    baseWeight: 0.7,
    minRegimeTier: 3,
    conflictTag: 'dimension_access',
    description: 'Violent tears in the bedrock floor open natural ramps and shafts leading into the silent, immutable Underworld.',
    mechanicalEffect: 'Generates bedrock breach down into sub-level',
  },
  {
    id: 'anomalousworld:sculk_bloom',
    name: 'Sub-Deep Resonance',
    category: AnomalyCategory.BIOME,
    baseWeight: 0.8,
    minRegimeTier: 3,
    conflictTag: 'biome_corruption',
    description: 'Sculk tendrils and catalysts naturally take root on surface stone, reacting to surface thunder and wind tremors.',
    mechanicalEffect: 'Surface stone replaced with sculk catalysts and shriekers',
  },
  {
    id: 'anomalousworld:inversion_pulse',
    name: 'Spatial Dissonance',
    category: AnomalyCategory.SPATIAL,
    baseWeight: 0.6,
    minRegimeTier: 4,
    conflictTag: 'spatial',
    description: 'Local coordinate vectors wrap upon themselves; walking straight forward for 100 blocks brings you back to your trail.',
    mechanicalEffect: 'Local position wrapping within region bounds',
  },
  {
    id: 'anomalousworld:thermal_inversion',
    name: 'Thermodynamic Inversion',
    category: AnomalyCategory.WEATHER,
    baseWeight: 0.9,
    minRegimeTier: 2,
    conflictTag: 'temperature',
    description: 'Snow falls in scorching deserts, while ice refuses to melt even adjacent to boiling lava streams.',
    mechanicalEffect: 'Local biome temperature gradient inverted (-1.0x)',
  },
  {
    id: 'anomalousworld:temporal_stutter',
    name: 'Entity Tick Stutter',
    category: AnomalyCategory.ENTITY,
    baseWeight: 0.75,
    minRegimeTier: 3,
    conflictTag: 'entity_physics',
    description: 'Passive and hostile mobs move in erratic, stroboscopic bursts, freezing in place every 3 seconds before snapping forward.',
    mechanicalEffect: 'Entity tick processing throttled to intermittent pulses',
  },
];
